base_size = 32;
state = "dormant"; // "dormant" | "warning" | "active"
time_dormant = 2.0;
time_warning = 1.0;
time_active = 1.8;
timer = random_range(0, time_dormant);
tick_damage = 9;
tick_interval = 0.4;
tick_timer = 0;
smoke_timer = 0;
is_up = false;
