event_inherited();

body_colour = c_aqua;
hp_max = 22;
hp = hp_max;
move_speed = 55;
contact_damage = 6;
preferred_range = 180;
attack_range = 220;
attack_cooldown = 1.4;
attack_cooldown_timer = 0;
attack_windup = 0.35;
attack_windup_timer = 0;
projectile_damage = 8;
projectile_speed = 220;
state = "patrol";
vision_range = 240;
vision_angle = 110;
spider_sense_range = 80;
patrol_radius = 130;
exp_reward = 20;
gold_reward = 7;
knockback_resistance = 0.25;
